apiVersion: apps/v1
kind: ReplicatSet
metadata:
  name: myapp-rs
  labels:
      app: myapp
      type: front-end
spec:
  template:

    metatada:
     name: myapp-pod
     labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector: 
    matchLabels:
       type: front-end